## Create a CI workflow to build the Docker image, but not push it to ECR. Use buildx to build and cache artifacts.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./hello-world
          file: ./hello-world/Dockerfile
          platforms: linux/amd64
          tags: events-poc:latest
          push: false
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{github.sha}}
          restore-keys: |
            ${{ runner.os }}-buildx-
